### PR TITLE
Convert to es6, fix phantomjs leak

### PR DESCRIPTION
**Pull request by gordlea**
Convert to use babel + es6 instead of coffeescript.
Phantomjs updated to latest.
Phantomjs no longer starts in the constructor.
Adds process.on('exit') listener to shutdown phantomjs.

Tests that the generated chart looks like it should. I've noticed when highcharts updates the look can change slightly, this will probably have to be tweaked going forwards.
Tests various recovery situations.

Adds configurable phantomjs response timeout, if response not recived by timeout (default 60s), job is re-added to the queue and phantomjs is restarted.

Also adds sleepTimeout, where phantomjs will be stopped after a configurable amount of time since the last render (defaults to 5 minutes, see readme for more details).

When you go to generate a report, highcharts-server will first try to connect to phantomjs on the configured port. If it finds one, then it will use it. If it can't find one, it will start a new instance of phantomjs and use that. This allows multiple workers on the same machine to share an instance of phantomjs.

### CODE REVIEW

**Comment by gordlea** [comment]
@ashleybrener I can squash this if you'd prefer.

**Comment by gordlea** [comment]
I wish i could see the diff.png from the failed travis build. 

```
Failures:
1) highcharts-server generates a chart that matches the original with < 0.1% difference
  Message:
    Expected 8.42 to be less than 0.1.
```

I'm guessing that might be due to different system fonts installed or something.

**Comment by ashbrener** [comment]
Thank you @gordlea, great work (!)

**Comment by gordlea** [comment]
@ashleybrener No problem! Do you think you could do an npm release of this soon? 

Also, any thoughts on incrementing the version to 1.0.0? It's a fairly major update.

**Comment by ashbrener** [comment]
Done.

**Pull request merged**
