### PR TITLE
Convert to es6, fix phantomjs leak

### PR DESCRIPTION
**Pull request by gordlea**
Convert to use babel + es6 instead of coffeescript.
Phantomjs  updated to latest.
Phantomjs no longer starts in the constructor.
Adds process.on('exit') listener to shutdown phantomjs.

When you go to generate a report, highcharts-server will first try to connect to phantomjs on the configured port. If it finds one, then it will use it. If it can't find one, it will start a new instance of phantomjs and use that. This allows multiple workers on the same machine to share an instance of phantomjs.

### CODE REVIEW

**Comment by gordlea** [comment]
Apologies, made PR against wrong branch.

**Comment by ashbrener** [comment]
@gordlea this looks good, I had intention to convert to es6 and fix the nasty lingering phantomjs process bug. Resend the PR and I'll merge it.

**Comment by ashbrener** [comment]
@gordlea are you still interested in merging this ?

**Comment by gordlea** [comment]
Hi @ashleybrener, apologies, I didn't see your response. I would be interested in merging this. I suppose I should add back in the .travis.yml files etc. Give me a bit and I'll get it ready.

**Comment by gordlea** [comment]
Actualy, I'll put together a new PR, with the latest changes.

**Comment by gordlea** [comment]
See #7

**Pull request closed without merging**
